# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - closed
    branches:
      - main # Specify the target branch (e.g., main, master, develop)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  archi_report:
    permissions:
      contents: write
      pages: write
    runs-on: self-hosted
    name: Deploy Archi report HTML to GitHub Pages
    steps:
      - name: Clen up 
        run: rm -rf /home/dexter/actions-runner/_work/ArchOps/ArchOps > /dev/null
     
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy Archi report
        id: archi
        uses: WoozyMasta/archimate-ci-image@5.7.0-1.0.6
        with:
          GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
          archiHtmlReportEnabled: true
          archiJasperReportEnabled: true
          archiJasperReportFormats: PDF,DOCX
          archiCsvReportEnabled: false
          archiExportModelEnabled: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
